/*
 * Copyright (c) 2010, Department of Information Engineering, University of Padova.
 * All rights reserved.
 *
 * This file is part of Lael.
 *
 * Lael is free software: you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * Lael is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Lael.  If not, see <http://www.gnu.org/licenses/>.
 *
 * ===================================================================================
 */

/**
 *
 * This is the application of the user interface. It shows the payload of the packages
 * sent by a single node and save the data to TXT files.
 * The payload contains this informations:
 * >> SensorsMsg:
 * [ID]         		identification number of the sensor
 * [Voltage(V)]  		voltage
 * [Temperature(°C)]	        temperature
 * [Humidity(%RH)]   		humidity
 * [Light(A/W)]			light
 * >> RadioMsg:
 * [ID]         		identification number of the sensor
 * [Counter]  			identification number of the packet
 * [RSSI(db)]	        	received signal strength indicator
 * [RSS(db)]	        	received signal strength
 * [LQI]   			link quality indicator
 * [Channel]			transmission channel
 * [Power]			transmission power

 * See the help of this program calling java DataSaver -h
 *
 * @date 16/11/2010 18:14
 * @author Filippo Zanella <filippo.zanella@dei.unipd.it>
 */

import java.io.*;
import java.lang.Math;
import net.tinyos.message.Message;
import net.tinyos.message.MessageListener;
import net.tinyos.message.MoteIF;
import net.tinyos.message.SerialPacket;
import net.tinyos.packet.BuildSource;
import net.tinyos.packet.PhoenixSource;
import net.tinyos.util.PrintStreamMessenger;
import java.util.Calendar;

public class DataSaver implements MessageListener
{
	private MoteIF mote;

	private SensorsMsg smsg;
	private RadioMsg rmsg;
	public FileOutputStream outputFileSensors;
	public FileOutputStream outputFileRadio;
	public PrintStream outputSensors;
	public PrintStream outputRadio;

	private Calendar cal;

	double temperature;
	double humidity;
	double light;
	double voltage;

	int rssi;
	int rss;
	int channel;
	int id;
	int power;
	int lqi;
	int counter;

	public DataSaver(MoteIF mif, String file, String source) {
		try
		{
			outputFileSensors = new FileOutputStream(file + "_sensors.txt");
			outputSensors = new PrintStream(outputFileSensors);
			outputSensors.println("##File generated by DataSaver ##");
			String curTime = (Calendar.getInstance().getTime()).toString();
			outputSensors.println(curTime);
			outputSensors.println("");
			outputSensors.println("[ID]\t[Voltage(V)]\t[Temperature(°C)]\t[Humidity(%RH)]\t[Light(A/W)]\t[Time(ms)]");
			outputSensors.println("");

			outputFileRadio = new FileOutputStream(file + "_radio.txt");
			outputRadio = new PrintStream(outputFileRadio);
			outputRadio.println("##File generated by DataSaver ##");
			outputRadio.println(curTime);
			outputRadio.println("");
			outputRadio.println("[ID]\t[RSS(dBm)]\t[RSSI(dBm)]\t[LQI(dBm)]\t[Ch]\t[Power]\t[Counter]\t[Time(ms)]");
			outputRadio.println("");

			System.out.println("Copyright (c) 2010, Department of Information Engineering, University of Padova.");
			System.out.println("");
			System.out.print("Connecting to serial port...");

			mote = mif;

			mote.registerListener(new SensorsMsg(), this);
			mote.registerListener(new RadioMsg(), this);
		}
		catch (IOException ioex) {
			System.err.println("Exception thrown when creating a file. Exiting.");
			System.err.println(ioex);
		}
		catch (Exception ex) {
			System.err.println("Couldn't contact serial port.");
			System.err.println(ex);
		}
		System.out.println("done.");
		System.out.println("Connected with " + source +  ".");
		System.out.println("DataSaver started.");
	}

	synchronized public void messageReceived(int dest, Message m) {

		if(m instanceof SensorsMsg) {
			smsg = (SensorsMsg) m;

			//temperature = -38.4 + 0.0098 * msg.get_temperature();
			temperature = -40 + 0.01 * smsg.get_temperature();
			//temperature = -39.6 + 0.01 * msg.get_temperature() -2*0.00000001 * Math.pow((msg.get_temperature() - 7000),2);

			humidity = -0.0000028*smsg.get_humidity()*smsg.get_humidity() + 0.0405*smsg.get_humidity()-4;
			light = smsg.get_light();
			voltage = (double)smsg.get_voltage()/(double)4096*3;

			long curTime = (Calendar.getInstance()).getTimeInMillis()/1000;

			/*	System.out.println("voltage: " + cutNumber(voltage,5) + " [V]");
				System.out.println("temperature: " + cutNumber(temperature,5) + " [C]");
				System.out.println("light: " + cutNumber(light,5) + " [?]");
				System.out.println("humidity: " + cutNumber(humidity,5) + " [%]");
					*/
					try												
			{
				outputSensors.println(smsg.get_id() + "\t" + "\t" + cutNumber(voltage,5)
					+ "\t" + cutNumber(temperature,5) + "\t" + cutNumber(humidity,5)
					+ "\t" + cutNumber(light,5) + "\t" + curTime);
			}
			catch (Exception e) {
				System.err.println("Exception thrown when writing the outputs. Exiting.");
				System.err.println(e);
			}
		}

		if(m instanceof RadioMsg) {
			rmsg = (RadioMsg) m;

			rssi = rmsg.get_rssi();
			rss = rmsg.get_rss();
			channel = rmsg.get_channel();
			id = rmsg.get_id();
			power = rmsg.get_power();
			lqi = rmsg.get_lqi();
			counter = rmsg.get_counter();

			long curTime = (Calendar.getInstance()).getTimeInMillis()/1000;

			/*	System.out.println("RSSI: " + cutNumber(rssi,5) + " [dB]");
				System.out.println("RSS: " + cutNumber(rss,5) + " [dB]");
				System.out.println("LQI: " + cutNumber(lqi,5));
				System.out.println("Channel: " + cutNumber(channel,5));
				System.out.println("Power: " + cutNumber(power,5));
				System.out.println("ID: " + cutNumber(id,5));
			System.out.println("Counter: " + cutNumber(counter,5));
					*/
					try												
			{
				outputRadio.println(id + "\t" + "\t" + rss
					+ "\t" + rssi + "\t" + lqi + "\t" + channel + "\t" + power + "\t" + counter + "\t" + curTime);
			}
			catch (Exception e) {
				System.err.println("Exception thrown when writing the outputs. Exiting.");
				System.err.println(e);
			}
		}
	}

	public String cutNumber(double str, int pos) {
		String s = str + "";
		if(pos>s.length())
			pos = s.length();
		return s.substring(0,pos);
	}

	private static void usage() {
		System.err.println("usage: DataSaver [options] [-comm SOURCE] [-f FILE]");
		System.err.println("options:");
		System.err.println("-h\t\t Show this help");
		System.err.println("[-comm SOURCE]\t Set the serial source connection");
		System.err.println("[-f FILE]\t Save the data to a <FILE>.txt");
		System.err.println("");
		System.err.println("The default command is: DataSaver -comm serial@/dev/ttyUSB0:tmote -f data");
	}

	public static void main(String[] args) {
		String  source = "serial@/dev/ttyUSB0:tmote";
		String  file = "dati";

		if(args.length == 1) {
			if (!args[0].equals("-h")) {
				usage();
				System.exit(1);
			}
		}
		if (args.length == 2) {
			if (!args[0].equals("-comm")) {
				usage();
				System.exit(1);
			}
			source = args[1];
		}
		else if (args.length == 4) {
			if (!args[0].equals("-comm")) {
				usage();
				System.exit(1);
			}
			source = args[1];
			file = args[3];
		}
		else if (args.length != 0) {
			usage();
			System.exit(1);
		}

		PhoenixSource phoenix;

		if (source == null) {
			phoenix = BuildSource.makePhoenix(PrintStreamMessenger.err);
		}
		else {
			phoenix = BuildSource.makePhoenix(source, PrintStreamMessenger.err);
		}

		MoteIF mif = new MoteIF(phoenix);
		new DataSaver(mif,file,source);
	}
}
